services:
  fastapi-app:
    build:
      context: ./backends/python-fastapi
      target: development
    ports:
      - 8000:8000
    volumes:
      - ./backends/python-fastapi:/app
      - fastapi-app-venv:/app/.venv
    command: [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--reload" ]
    tty: true

  svelte-app:
    build:
      context: ./frontends/typescript-svelte
      target: development
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - ./frontends/typescript-svelte:/app
      - svelte-app-node-modules:/app/node_modules
    command: /bin/sh -c "npm install && npm run dev"

volumes:
  fastapi-app-venv:
  svelte-app-node-modules:
