services:
  fastapi-app:
    build:
      context: ./backends/python-fastapi
      target: development
    ports:
      - 8000:8000
    volumes:
      - ./backends/python-fastapi:/app
      - fastapi-app-venv:/app/.venv
    command: [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--reload" ]
    tty: true

  express-app:
    build:
      context: ./backends/typescript-express
      target: development
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./backends/typescript-express:/app
      - express-app-node-modules:/app/node_modules
    command: /bin/sh -c "npm ci && npm run dev"
    tty: true

  gin-app:
    build:
      context: ./backends/go-gin
      target: development
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./backends/go-gin:/app
    command: go run main.go
    tty: true

  svelte-app:
    depends_on:
      - fastapi-app
      - express-app
    build:
      context: ./frontends/typescript-svelte
      target: development
      args:
        VITE_FASTAPI_PROXY_TARGET: http://fastapi-app:8000
        VITE_EXPRESS_PROXY_TARGET: http://express-app:3000
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - ./frontends/typescript-svelte:/app
      - svelte-app-node-modules:/app/node_modules
    command: /bin/sh -c "npm ci && npm run dev"

volumes:
  fastapi-app-venv:
  express-app-node-modules:
  svelte-app-node-modules:
